// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService is a Wails-bound service. In S2 it drives the REAL tachi agent
 * (RunConversationStream) when configured, falling back to a simulated turn
 * otherwise.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActivateSession makes id the displayed session and ensures its per-session
 * agent/manager is ready, WITHOUT reloading message history. Lightweight
 * counterpart to LoadSession for switching to a session already in the cache.
 */
export function ActivateSession(id: string): $CancellablePromise<string> {
    return $Call.ByID(2022663295, id);
}

/**
 * AddSessionRoots appends directories the user picked to the session's root set.
 * Returns "ok", or a human-readable reason the UI shows instead (see the validation
 * rules at the top of this file).
 */
export function AddSessionRoots(id: string, dirs: string[] | null): $CancellablePromise<string> {
    return $Call.ByID(541268238, id, dirs);
}

/**
 * AnswerQuestion delivers the user's answers to a session's pending
 * AskUserQuestion, unblocking the agent loop.
 * 
 * Answers are keyed by the full question text, with values holding the selected
 * option labels (and any free text) joined with ", " — the convention the TUI
 * established, so the model sees one consistent shape whichever frontend asked.
 * Empty answers mean the user declined/cancelled: the model is told the question
 * went unanswered rather than being handed a made-up choice.
 */
export function AnswerQuestion(sessionID: string, answers: { [_ in string]?: string } | null, annotations: { [_ in string]?: string } | null): $CancellablePromise<string> {
    return $Call.ByID(762833678, sessionID, answers, annotations);
}

/**
 * CurrentSession returns the active (displayed) session (nil if none).
 */
export function CurrentSession(): $CancellablePromise<$models.SessionInfo | null> {
    return $Call.ByID(1225632939);
}

/**
 * DeletePlan removes one of this session's plan files and returns "ok".
 * 
 * The path comes from the frontend, so it is validated against this session's own plan
 * files first: a binding that deletes whatever it is handed is an arbitrary-file-delete
 * primitive, and this one is reachable from a UI listing.
 */
export function DeletePlan(sessionID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(640413536, sessionID, path);
}

/**
 * DeleteSession deletes a session and its per-session run state. If the
 * deleted session is the currently displayed one, activeID is cleared so the
 * UI falls back to choosing/creating a session.
 */
export function DeleteSession(id: string): $CancellablePromise<string> {
    return $Call.ByID(3827341809, id);
}

/**
 * GetContextInfo returns the context-usage breakdown for the session the ring
 * belongs to. An unknown session (or one whose agent is not built yet) yields
 * the zero value, which the frontend renders as "not measured yet".
 */
export function GetContextInfo(id: string): $CancellablePromise<$models.ContextInfoVO> {
    return $Call.ByID(3932100687, id);
}

/**
 * GetMode returns the active session's mode: auto, chat or plan.
 */
export function GetMode(): $CancellablePromise<string> {
    return $Call.ByID(2005017131);
}

/**
 * GetPlan returns one of this session's plans — the newest when path is empty, otherwise
 * the plan at path (which must be one of this session's own plan files).
 * 
 * The list travels with the payload: a session can hold several plans, and the panel
 * shows both the one you are reading and how many others are there.
 */
export function GetPlan(sessionID: string, path: string): $CancellablePromise<$models.PlanVO> {
    return $Call.ByID(2856990187, sessionID, path);
}

/**
 * GetProviderInfo returns the active session's provider/model/context-window.
 */
export function GetProviderInfo(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(1350822389);
}

/**
 * GetSessionRoots returns the session's root set for the UI, with each additional
 * root's current existence. It never fails: an unknown session yields the zero
 * value, which the UI renders as "no roots yet".
 */
export function GetSessionRoots(id: string): $CancellablePromise<$models.SessionRootsVO> {
    return $Call.ByID(2545630373, id);
}

/**
 * GetSessionUsage returns the session's cumulative cost (CNY) and ledger
 * credit ("积分") for the status bar. Both are 0 when no usage is recorded.
 */
export function GetSessionUsage(id: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(388515563, id);
}

/**
 * GetSessionWorkingDir returns the session's working directory ("" if unset).
 */
export function GetSessionWorkingDir(id: string): $CancellablePromise<string> {
    return $Call.ByID(3373593390, id);
}

/**
 * GetState returns the current agent state.
 */
export function GetState(): $CancellablePromise<$models.AgentState> {
    return $Call.ByID(637370013);
}

/**
 * GetThinkingLevel returns the active session's thinking level. Empty =
 * follow the provider default (surfaced as "default").
 */
export function GetThinkingLevel(): $CancellablePromise<string> {
    return $Call.ByID(3496856430);
}

/**
 * GetTurnDiff returns the working-tree diff of paths (the files a turn touched) under
 * the session's workspace. An empty paths list means the whole tree.
 */
export function GetTurnDiff(sessionID: string, paths: string[] | null): $CancellablePromise<$models.TurnDiffVO> {
    return $Call.ByID(2623298140, sessionID, paths);
}

export function GetUIState(): $CancellablePromise<$models.UIStateVO> {
    return $Call.ByID(518078095);
}

/**
 * ListCommands returns the slash commands the desktop supports, in registry
 * order (which is what the palette shows).
 */
export function ListCommands(): $CancellablePromise<$models.CommandVO[] | null> {
    return $Call.ByID(3190975402);
}

/**
 * ListMCPProfiles returns the active MCP profile and all available profiles
 * (mcp.<name>.json in global/project scope).
 */
export function ListMCPProfiles(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3487132922);
}

/**
 * ListMCPServers returns all configured MCP servers with their tools and, for
 * each tool, whether it is loaded (discovered/opt-in) in the CURRENT session.
 * Only connected servers expose their tools (the pool); disabled ones show
 * with no tools until connected.
 */
export function ListMCPServers(): $CancellablePromise<$models.MCPServerVO[] | null> {
    return $Call.ByID(2900398080);
}

/**
 * ListOneOffs lists this session's side-channel runs, newest first.
 * 
 * It reads each record's header line and its file metadata only. The full parse is
 * LoadOneOff's job, for the one run the reader is actually looking at.
 */
export function ListOneOffs(sessionID: string): $CancellablePromise<$models.OneOffListVO> {
    return $Call.ByID(1198975034, sessionID);
}

/**
 * ListProviders returns the configured providers (priority-ordered).
 */
export function ListProviders(): $CancellablePromise<config$0.ProviderConfig[] | null> {
    return $Call.ByID(522595286);
}

/**
 * ListSessions returns all tachi sessions, most recently updated first.
 */
export function ListSessions(): $CancellablePromise<$models.SessionInfo[] | null> {
    return $Call.ByID(3651696153);
}

/**
 * LoadOneOff reads one run: its messages (in the transcript's own shape) plus the API-call
 * summaries. Prompt text is left out — see OneOffRequestVO.
 */
export function LoadOneOff(sessionID: string, name: string): $CancellablePromise<$models.OneOffDetailVO> {
    return $Call.ByID(1996979929, sessionID, name);
}

/**
 * LoadOneOffRequest returns one LLM call in full, prompts included, by its Seq. It is a
 * separate call because the prompts are over half of a record's bytes and only a reader
 * who asked for them should pay for them.
 */
export function LoadOneOffRequest(sessionID: string, name: string, seq: number): $CancellablePromise<$models.OneOffRequestVO> {
    return $Call.ByID(2847462494, sessionID, name, seq);
}

/**
 * LoadSession loads the most recent `limit` raw messages of a session, makes it
 * current (repointing the desktop's active session at its per-session
 * agent/manager), restores its LLM history, and reports whether older messages
 * remain. limit <= 0 falls back to the default page size.
 */
export function LoadSession(id: string, limit: number): $CancellablePromise<$models.SessionPage> {
    return $Call.ByID(2071478940, id, limit);
}

/**
 * LoadSessionMore loads up to `limit` raw messages strictly older than `before`
 * (RFC3339, the oldest already-loaded message), for the given session. It does
 * NOT change the active session — it is the "scroll up" counterpart to
 * LoadSession used after the initial page.
 */
export function LoadSessionMore(id: string, before: string, limit: number): $CancellablePromise<$models.SessionPage> {
    return $Call.ByID(907264229, id, before, limit);
}

/**
 * NewSession creates a fresh session and its own per-session agent, making it
 * active. The in-memory history starts empty.
 */
export function NewSession(): $CancellablePromise<$models.SessionInfo> {
    return $Call.ByID(3312312366);
}

/**
 * OpenPath opens a file (or directory) with the system default application.
 */
export function OpenPath(path: string): $CancellablePromise<string> {
    return $Call.ByID(885956971, path);
}

/**
 * PreviewFile describes the attachment at path and, when withContent is set,
 * returns the content of its text and table kinds.
 * 
 * It never fails outright: a missing file, a directory and an unreadable file are
 * all ordinary in a transcript that remembers a SendFile from an earlier run, and
 * each has a sentence the card can render. A deleted report.md comes back as
 * kindMissing, not as an error the UI would have to invent wording for.
 */
export function PreviewFile(path: string, withContent: boolean): $CancellablePromise<$models.FilePreviewVO> {
    return $Call.ByID(2752159294, path, withContent);
}

/**
 * RemoveSessionRoot drops one additional root. The primary is not removable (the
 * UI offers "change" instead), so a path equal to it is simply not found here.
 */
export function RemoveSessionRoot(id: string, dir: string): $CancellablePromise<string> {
    return $Call.ByID(2668803664, id, dir);
}

/**
 * RenameSession sets a session's title (used by the sidebar rename action).
 */
export function RenameSession(id: string, title: string): $CancellablePromise<string> {
    return $Call.ByID(1629291394, id, title);
}

/**
 * ResolveDroppedPaths maps paths dropped onto the window into @-references for
 * a session, skipping paths that no longer exist.
 */
export function ResolveDroppedPaths(sessionID: string, paths: string[] | null): $CancellablePromise<$models.DroppedFileVO[] | null> {
    return $Call.ByID(1148759874, sessionID, paths);
}

/**
 * RevealPath shows the file in Finder.
 */
export function RevealPath(path: string): $CancellablePromise<string> {
    return $Call.ByID(1709803226, path);
}

/**
 * ReviewChanges runs a review SCOPED to the files a turn changed: the desktop's
 * turn-level entry, one click next to the diff chip. It runs as a turn — the session
 * goes busy, Stop cancels it, and the reviewer's ReportFinding calls are counted for the
 * frontend's one-line anchor — but its process goes to the side-channel lane: the
 * conversation keeps one line about the review, and the panel shows the rest.
 * 
 * reviewedMsg is the id of the turn whose footer was clicked. It is recorded WITH the run
 * (agent.ReviewOrigin) because that pairing is otherwise only in the frontend's memory: a
 * restart would lose it, and the turn could no longer say 已评审 N 条.
 * 
 * Returns "" when the run started, or a reason the UI shows instead.
 */
export function ReviewChanges(sessionID: string, paths: string[] | null, reviewedMsg: string): $CancellablePromise<string> {
    return $Call.ByID(1435759713, sessionID, paths, reviewedMsg);
}

/**
 * RunCommand runs a slash command for the displayed session. It returns "" when
 * the command started, or a human-readable reason when it did not — the
 * frontend shows that as a notice in the transcript instead of pretending a
 * turn happened.
 */
export function RunCommand(text: string): $CancellablePromise<string> {
    return $Call.ByID(2481277094, text);
}

/**
 * RunningSessions returns the IDs of sessions with an in-flight turn.
 */
export function RunningSessions(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3792694786);
}

/**
 * SearchFiles returns @-file completion matches for a session.
 * 
 * The whole root set is searched (primary + the session's additional roots): an
 * additional root is invisible to a primary-only index, and "I added the folder,
 * why can't it see it" is the gap this closes. Three rules keep the merged list
 * honest:
 * 
 *   - each root gets its own share of the limit, so one large root cannot crowd
 *     the others out of the list;
 *   - a file reachable through two roots (nested roots, e.g. primary=/repo/pkg
 *     with /repo added) appears ONCE, attributed to the primary — the relative
 *     reference is the stable one;
 *   - a root that cannot be listed (deleted, unmounted, no ripgrep) contributes
 *     nothing instead of failing the whole search.
 */
export function SearchFiles(sessionID: string, query: string, limit: number): $CancellablePromise<$models.FileMatchVO[] | null> {
    return $Call.ByID(776280719, sessionID, query, limit);
}

/**
 * SendMessage starts a turn. It returns immediately; state changes are
 * streamed to the frontend via the "agent:state" event and to the menu bar.
 */
export function SendMessage(text: string): $CancellablePromise<string> {
    return $Call.ByID(729126489, text);
}

/**
 * SetMCPProfile switches the active MCP profile at runtime (reverts on restart).
 * It uses the current session's agent (whose manager is the shared one) and
 * reconciles the connected servers via SwitchMCPProfile.
 */
export function SetMCPProfile(name: string): $CancellablePromise<string> {
    return $Call.ByID(1957064157, name);
}

/**
 * SetMCPServerEnabled connects (enabled=true) or disconnects (enabled=false) a
 * configured MCP server at runtime. It does NOT persist to mcp.json — the
 * change is runtime-only (restart reverts to config).
 */
export function SetMCPServerEnabled(name: string, enabled: boolean): $CancellablePromise<string> {
    return $Call.ByID(2496346776, name, enabled);
}

/**
 * SetMCPToolEnabled toggles a single MCP tool for the CURRENT session:
 * enabled marks it discovered/opt-in (and registers it with the session's
 * agent so it is immediately usable); disabled removes it (and unregisters it).
 * Per-session only — no global persistence.
 */
export function SetMCPToolEnabled(name: string, enabled: boolean): $CancellablePromise<string> {
    return $Call.ByID(2404192207, name, enabled);
}

/**
 * SetMode switches the active session's mode and returns "ok", or a sentence saying why
 * it could not (no agent yet, unknown mode, a turn in flight).
 * 
 * A mode is not just a label: chat and plan hide the destructive tools from the schema
 * the model sees, and plan additionally appends the plan-mode rules to the system prompt.
 * That filter runs every iteration, so switching mid-turn would pull tools out from under
 * a running agent — a running session has to wait.
 */
export function SetMode(mode: string): $CancellablePromise<string> {
    return $Call.ByID(4069889863, mode);
}

/**
 * SetOneOffPanelOpen records whether the side-channel panel is open. Written on every toggle
 * and best effort, like the rest of uiState: a failure costs the next launch the panel's
 * position and nothing else.
 */
export function SetOneOffPanelOpen(open: boolean): $CancellablePromise<void> {
    return $Call.ByID(1790273073, open);
}

/**
 * SetOneOffPanelWidth records how wide the reader made the panel. The value is refused when it
 * is outside the panel's bounds: this is a hand-editable file, and a width the layout cannot
 * honour is worse than the default it falls back to.
 */
export function SetOneOffPanelWidth(px: number): $CancellablePromise<void> {
    return $Call.ByID(4191208727, px);
}

/**
 * SetSessionWorkingDir changes the session's working directory and persists it
 * to session meta. The NEXT turn runs tools under this directory (per-turn
 * wdctx injection, like channel agent_turn.go). Returns "ok" on success.
 */
export function SetSessionWorkingDir(id: string, dir: string): $CancellablePromise<string> {
    return $Call.ByID(2110354194, id, dir);
}

/**
 * SetThinkingLevel sets the active session's thinking level. "default"/""
 * means DON'T set it — follow the provider's own default; "none" disables
 * thinking. Persisted to the session's metadata.
 */
export function SetThinkingLevel(level: string): $CancellablePromise<string> {
    return $Call.ByID(2835565002, level);
}

/**
 * Steer answers the agent's steer_check for a session: it delivers the text
 * the frontend queued while the turn was running so the agent loop can inject
 * it at the current steer point (after the just-finished tool calls, before
 * the next LLM call). Empty text is the "nothing queued" signal that simply
 * unblocks the loop.
 * 
 * The channel is drained before writing so a reply that races a timed-out or
 * already-answered steer point can neither wedge the loop nor leave a stale
 * value behind for the next steer point to consume.
 */
export function Steer(sessionID: string, text: string): $CancellablePromise<string> {
    return $Call.ByID(2451555629, sessionID, text);
}

/**
 * Stop aborts the current turn (real agent via cancel, or simulated) and
 * returns to idle.
 */
export function Stop(): $CancellablePromise<string> {
    return $Call.ByID(1357919908);
}

/**
 * StopAndSend stops the current turn (if any) and immediately starts a new one
 * with text — the "send now" action for the pending queue. Unlike Stop
 * followed by SendMessage, it waits for the previous turn's goroutine to fully
 * exit first, so the new turn can never race the old one for run state. In the
 * simulated fallback it stops the sim and waits for it to wind down.
 */
export function StopAndSend(text: string): $CancellablePromise<string> {
    return $Call.ByID(1733339567, text);
}

/**
 * SwitchProvider switches the active session's agent to the given config
 * provider, persisting it to that session's metadata (like TUI does).
 */
export function SwitchProvider(name: string): $CancellablePromise<string> {
    return $Call.ByID(1503034677, name);
}
