// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "../agent/tools/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as linediff$0 from "../pkg/linediff/models.js";

/**
 * AgentState is the payload pushed to the frontend (and shown in the menu bar).
 */
export interface AgentState {
    "status": AgentStatus;

    /**
     * short menu-bar text, e.g. "思考"
     */
    "label": string;

    /**
     * one-line human description
     */
    "detail": string;
}

/**
 * AgentStatus enumerates the runtime states the agent can be in. These are
 * derived from the real AgentEvent stream.
 */
export enum AgentStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusIdle = "idle",
    StatusThinking = "thinking",
    StatusToolRunning = "tool_running",
    StatusBusy = "busy",
    StatusError = "error",
};

/**
 * AskEvent is emitted to the frontend when the agent asks the user questions
 * (the AskUserQuestion tool). The turn is parked on the answer channel until the
 * frontend replies via AgentService.AnswerQuestion — same mechanism the TUI uses
 * through AIAgent.RespondToAskUser.
 */
export interface AskEvent {
    "sessionId": string;
    "toolId": string;
    "questions": tools$0.Question[] | null;
}

/**
 * CommandVO describes a slash command for the composer's "/" palette.
 */
export interface CommandVO {
    "name": string;
    "description": string;
    "inputHint"?: string;
}

/**
 * ContextInfoVO is the ring's popover payload. Estimate is the total of Parts
 * (0 = nothing measured yet); ContextWindow is 0 when the model's window is
 * unknown, in which case the frontend shows tokens without a percentage.
 */
export interface ContextInfoVO {
    "estimate": number;
    "contextWindow": number;
    "parts": ContextPartVO[] | null;
}

/**
 * ContextPartVO is one bucket of the local input-token estimate. Key is stable
 * and doubles as the frontend's colour hook (--ctx-<key> in base.css); Label is
 * the wording the popover shows.
 */
export interface ContextPartVO {
    "key": string;
    "label": string;
    "tokens": number;
}

/**
 * DroppedFileVO describes one dropped file as it will be referenced.
 */
export interface DroppedFileVO {
    /**
     * "@relative/path", inserted into the input
     */
    "ref": string;

    /**
     * base name, for the UI chip/tooltip
     */
    "name": string;
    "isDir": boolean;

    /**
     * dir | image | text | binary | missing
     */
    "kind": string;

    /**
     * bytes (0 for directories)
     */
    "size": number;
}

/**
 * FileChangeVO carries one tool call's change to the frontend.
 */
export interface FileChangeVO {
    "path": string;

    /**
     * Hunks are render-ready lines (context/add/del) carrying fragment-relative line
     * numbers, which the UI deliberately does not display: a fragment has no position
     * in the file, and showing 1,2,3 would read as file coordinates (see the linediff
     * package comment for why they are computed anyway).
     */
    "hunks": linediff$0.Hunk[] | null;

    /**
     * Added/Removed are FRAGMENT line counts, not git numstat.
     */
    "added": number;
    "removed": number;

    /**
     * ReplaceAll marks a call that replaced every occurrence. A fragment diff can only
     * show one block against another, so the card labels it rather than implying the
     * changes were paired up.
     */
    "replaceAll": boolean;
}

/**
 * FileDiffVO is one file's working-tree change.
 */
export interface FileDiffVO {
    "path": string;
    "oldPath"?: string;
    "created"?: boolean;
    "deleted"?: boolean;
    "binary"?: boolean;
    "hunks": linediff$0.Hunk[] | null;
    "added": number;
    "removed": number;
}

/**
 * FileDropEvent is emitted to the frontend when files are dropped onto the
 * window. Paths are the raw native paths; the frontend asks for @-references
 * via ResolveDroppedPaths (which needs the session the drop landed in).
 */
export interface FileDropEvent {
    "paths": string[] | null;
    "elementId": string;
}

/**
 * FileMatchVO is one @-file completion match, relative to the search root.
 */
export interface FileMatchVO {
    /**
     * Path is what the picker SHOWS: always relative to the root the match came
     * from (that is what keeps a row readable — "[shared-lib] src/x.go").
     */
    "path": string;
    "isDir": boolean;

    /**
     * Ref is the complete reference to insert into the input, '@' included. It is
     * the authoritative form: a match under the primary root resolves to "@rel",
     * one under an additional root to an absolute "@abs" (agent/atfile.RefForPath
     * decides, so the rule lives in one place).
     */
    "ref": string;

    /**
     * Root labels where the match came from: "" for the primary root, otherwise the
     * root's base name — or its full path when two roots share a base name.
     */
    "root": string;
}

/**
 * FilePreviewVO describes one attachment to its card. It is served in two
 * stages: metadata alone when the card mounts, then the same struct with Text
 * filled once the user expands the preview.
 */
export interface FilePreviewVO {
    "path": string;
    "name": string;

    /**
     * Kind decides how the card renders the file (one of the kind constants).
     */
    "kind": string;

    /**
     * Size is the file's size in bytes (0 for directories and missing paths), for
     * the card's "README.md · 12.4 KB" line.
     */
    "size": number;

    /**
     * Language is the highlight.js language for text kinds, "" when the file is
     * plain text (or not text at all).
     */
    "language": string;

    /**
     * Previewable says whether the card should offer a preview. Derived here
     * rather than in the frontend so the kind table stays in one place.
     */
    "previewable": boolean;

    /**
     * Text is the file's content, only for the text kinds and only when the
     * caller asked for content. Images, HTML and PDF are served straight from
     * disk by the /local asset handler instead, which is what lets a large file
     * stream rather than arrive as one string.
     */
    "text": string;

    /**
     * Rows is the parsed table of a CSV preview (row 0 is the header, per the
     * spreadsheet convention). The parsing lives here rather than in the
     * frontend: quoted fields, embedded newlines and European ";" separators are
     * what a real export contains, and encoding/csv already knows all of it.
     */
    "rows": (string[] | null)[] | null;

    /**
     * Truncated marks the content as the beginning of a larger file: Text past
     * maxPreviewBytes, a table past maxCSVRows.
     */
    "truncated": boolean;

    /**
     * Error is set when the file is there but could not be read; Kind then still
     * says what it would have been.
     */
    "error": string;
}

/**
 * FindingVO is one review finding as the panel renders it.
 */
export interface FindingVO {
    "path": string;
    "line": number;
    "endLine"?: number;
    "severity": string;
    "category"?: string;
    "text": string;
    "suggestion"?: string;
}

/**
 * MCPServerVO describes an MCP server and its tools for the status-bar panel.
 */
export interface MCPServerVO {
    "name": string;
    "type": string;
    "connected": boolean;
    "tools": MCPToolVO[] | null;
}

/**
 * MCPToolVO describes one tool under an MCP server for the status-bar panel.
 */
export interface MCPToolVO {
    /**
     * full name "mcp__server__tool"
     */
    "name": string;

    /**
     * original MCP name (no prefix)
     */
    "toolName": string;
    "description"?: string;
    "loaded": boolean;
}

/**
 * OneOffDetailVO is one run's replayable content.
 */
export interface OneOffDetailVO {
    "header": OneOffVO;

    /**
     * Messages are the run's raw messages in the same shape the transcript uses, so the
     * frontend renders them with the same bubbles and tool cards.
     */
    "messages": SessionMessage[] | null;

    /**
     * Requests are the API-call summaries (no prompt text — see OneOffRequestVO).
     */
    "requests"?: OneOffRequestVO[] | null;

    /**
     * Findings are the ReportFinding calls THIS run made — the run's own, not "the newest
     * review in the session" (see GetReviewFindings for that other question). It is what the
     * panel's findings pane shows for whichever run the reader selected.
     */
    "findings"?: FindingVO[] | null;

    /**
     * Notice explains a failure: bad name, unreadable file, unreadable record.
     */
    "notice"?: string;
}

/**
 * OneOffListVO is the panel's list payload.
 */
export interface OneOffListVO {
    /**
     * Items are this session's side-channel runs, newest first.
     */
    "items": OneOffVO[] | null;

    /**
     * Note says in the user's words why the list is empty: no such session, no record
     * directory, or nothing recorded yet. "Nothing here" and "could not look" are
     * different facts, and a silent empty list tells the reader neither.
     */
    "note"?: string;
}

/**
 * OneOffRequestVO is one LLM call inside a run. The summary (LoadOneOff) carries the
 * metadata and the tool NAMES; the full version (LoadOneOffRequest) adds the prompts.
 * 
 * The prompts are the reason this is separate: a record averages ~16KB of request payload
 * per call (the system prompt and tool schemas are resent every iteration), which is over
 * half the file. The panel should not pay for it to open a run, and a reader who asks
 * "what was the reviewer actually told" should get it on demand.
 */
export interface OneOffRequestVO {
    "seq": number;
    "iteration"?: number;
    "timestamp"?: string;
    "provider"?: string;
    "model"?: string;
    "thinking"?: string;
    "durationMs"?: number;
    "tools"?: string[] | null;
    "systemPrompt"?: string;
    "userPrompt"?: string;

    /**
     * Notice explains a failure of the lazy fetch (the summaries never carry one).
     */
    "notice"?: string;
}

/**
 * OneOffVO is one run (one record file) as the list and the panel header show it.
 */
export interface OneOffVO {
    /**
     * Name is the record file name — the list's key and what LoadOneOff takes.
     */
    "name": string;

    /**
     * Run groups the records of one batch: a multi-round review writes one file per
     * round, all sharing the orchestrator-owned report directory, which is therefore the
     * only reliable key (the file name's second-precision timestamp can straddle a
     * second). Falls back to Name when the record carries no report.
     */
    "run": string;

    /**
     * Kind is the raw recorded kind: review / commit / review-round-N.
     */
    "kind": string;

    /**
     * Round is the round number inside a multi-round review (0 = single-round).
     */
    "round"?: number;
    "sessionId"?: string;
    "provider"?: string;
    "model"?: string;

    /**
     * StartedAt is the meta header's start time (RFC3339, "" when unrecorded).
     */
    "startedAt"?: string;

    /**
     * UpdatedAt is the record file's last write — for a finished run, effectively its end.
     */
    "updatedAt"?: string;

    /**
     * Running is the mtime heuristic: the file was written to within
     * oneOffRunningWindow.
     */
    "running"?: boolean;

    /**
     * Report is where the run's human-readable report landed (agent.OneOffKeyReport).
     */
    "report"?: string;

    /**
     * ReviewedMsg is the conversation message this run was started for (a review's entry
     * records it), which is what lets a turn's chip say 已评审 after a restart.
     */
    "reviewedMsg"?: string;

    /**
     * Paths is the file set a scoped review was limited to (nil for a whole-tree review).
     * The diff pane needs it to show anything, and it is a property of the turn that asked,
     * so the record is where it has to live.
     */
    "paths"?: string[] | null;

    /**
     * Findings counts the run's ReportFinding calls. Only LoadOneOff fills it: counting
     * means reading the whole file, and paying that for every record in the list is not
     * worth it (the panel shows the count once a run is selected).
     */
    "findings"?: number;
}

/**
 * PlanEntryVO is one row of the plan panel's list: enough to choose between a session's
 * plans without loading them all. A session accumulates plans (one file per plan), so the
 * list is the difference between "the newest plan" and "the plans".
 */
export interface PlanEntryVO {
    "title": string;
    "path": string;
    "done": number;
    "total": number;
    "updatedAt"?: string;
}

/**
 * PlanStepVO is one step of a plan as the panel renders it.
 */
export interface PlanStepVO {
    "content": string;
    "status": string;
}

/**
 * PlanVO is the plan panel's payload: the plan being shown, plus the session's list.
 */
export interface PlanVO {
    "title": string;
    "content": string;
    "steps": PlanStepVO[] | null;

    /**
     * Path is where the plan lives, so the panel can offer the same 预览/打开 the
     * rest of the app uses for files.
     */
    "path"?: string;

    /**
     * UpdatedAt is the file's mtime (RFC3339): a plan is a document you revisit, and
     * "when was this last touched" is what tells you whether it still describes the
     * work in front of you.
     */
    "updatedAt"?: string;

    /**
     * Plans lists every plan this session still has (newest first), the shown one
     * included — the UI needs to say "3 of 5" without a second round-trip.
     */
    "plans"?: PlanEntryVO[] | null;

    /**
     * Note explains an empty plan (none yet, unreadable) — an empty panel and a panel
     * with nothing to say are different states.
     */
    "note"?: string;
}

/**
 * SessionInfo is a lightweight session summary for the sidebar list.
 */
export interface SessionInfo {
    "id": string;
    "title": string;
    "provider": string;
    "createdAt": string;
    "updatedAt": string;

    /**
     * CompactedParentID names the session this one was compacted FROM ("" when it was not). It is
     * the one piece of the compaction chain the sidebar needs: a chain is ONE conversation, and the
     * frontend folds a parent under the child it became. The child is the newest link, so a fresh
     * launch can rebuild the same shape from meta.json — which the frontend's own memory of the
     * live switch (agent:session_switched) could not do.
     */
    "compactedParentId"?: string;
}

/**
 * SessionMessage mirrors a raw session message (with iteration/seq/timestamp)
 * so the frontend can reconstruct the true in-turn ordering and show timestamps.
 */
export interface SessionMessage {
    /**
     * user/assistant/tool_call/tool_result/reminder
     */
    "role": string;
    "content": string;

    /**
     * RFC3339
     */
    "timestamp"?: string;

    /**
     * 1-based LLM call within the turn
     */
    "iteration"?: number;

    /**
     * session-wide request # (0 = not request-bound)
     */
    "seq"?: number;
    "thinking"?: string;
    "toolCalls"?: ToolCallVo[] | null;
    "toolName"?: string;
    "toolResult"?: string;
    "toolCallId"?: string;

    /**
     * human-readable args summary
     */
    "title"?: string;

    /**
     * raw JSON args
     */
    "args"?: string;
    "isError"?: boolean;

    /**
     * Change is the file change this tool call set out to make (nil for tools that
     * change no text). It is DERIVED from Args, never persisted, so reloading any old
     * session shows the same diffs with no migration.
     */
    "change"?: FileChangeVO | null;
}

/**
 * SessionPage is a page of a session's raw messages plus whether older
 * messages remain to be loaded.
 */
export interface SessionPage {
    "messages": SessionMessage[] | null;
    "hasMore": boolean;
}

/**
 * SessionRootVO is one additional root as the UI sees it.
 */
export interface SessionRootVO {
    "path": string;

    /**
     * Exists is false when the directory has since been removed or unmounted: the
     * UI greys the entry out, and the prompt no longer advertises it.
     */
    "exists": boolean;
}

/**
 * SessionRootsVO is a session's full root set.
 */
export interface SessionRootsVO {
    "primary": string;
    "additional": SessionRootVO[] | null;
}

/**
 * ToolCallVo is a minimal tool-call descriptor for rendering a tool card.
 */
export interface ToolCallVo {
    "name": string;
    "id": string;

    /**
     * human-readable args summary (reuses tools.ToolArgsSummary)
     */
    "title"?: string;

    /**
     * raw JSON args for full view
     */
    "arguments"?: string;
}

/**
 * TurnDiffVO is the changes panel's payload.
 */
export interface TurnDiffVO {
    /**
     * Files are the requested paths that differ from HEAD, tracked ones in git's
     * order, then untracked ones — stable between opens.
     */
    "files": FileDiffVO[] | null;

    /**
     * Root is the workspace the diff was taken in ("" when the session has none).
     */
    "root"?: string;

    /**
     * Note says in the user's words why the list is empty or incomplete: no
     * workspace, not a git repository, paths outside it, output truncated.
     */
    "note"?: string;

    /**
     * Ignored counts the requested paths git ignores (and therefore never diffs). It is a
     * typed half of Note for callers that have to act on it — 「评审本轮改动」 refuses on an
     * empty diff, and its refusal has to say "the reviewer cannot see this file" rather than
     * "there is nothing to review".
     */
    "ignored"?: number;
}

/**
 * GetUIState returns the desktop-only UI preferences the frontend owns.
 * 
 * The frontend keeps its own copy (React state drives the frame) and reads this once at
 * mount: the file is the durable half, not the source of truth for what is on screen.
 */
export interface UIStateVO {
    /**
     * OneOffPanelOpen is whether the side-channel panel was open last time.
     */
    "oneOffPanelOpen": boolean;

    /**
     * OneOffPanelWidth is that panel's width in CSS pixels; 0 means "never dragged".
     */
    "oneOffPanelWidth"?: number;
}
