// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Hunk is one render-ready line of a fragment diff. The JSON tags matter: this type
 * crosses into the desktop frontend (via FileChangeVO), where every other field is
 * camelCase.
 */
export interface Hunk {
    "kind": Kind;
    "oldLine": number;
    "newLine": number;
    "text": string;
}

/**
 * Kind classifies one hunk line.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * KindContext is a line both fragments share.
     */
    KindContext = "context",

    /**
     * KindAdd is a line only the new fragment has.
     */
    KindAdd = "add",

    /**
     * KindDel is a line only the old fragment has.
     */
    KindDel = "del",
};
