// Package deepresearch provides a config-driven deep research engine.
//
// The engine orchestrates a recursive search tree where each level:
//  1. Generates 'breadth' search queries via a direct LLM call
//  2. Launches parallel SubAgents to search + extract learnings
//  3. If depth > 0 and new learnings exist, recurses with depth-1 and breadth/2
//  4. Writes a final report via SubAgent or direct LLM call
//
// DeepResearch is NOT a tool — it is only accessible via the /research
// slash command. The engine is a plain Go struct, decoupled from the
// agent's tool registry, that handlers use directly.
package deepresearch

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"sync"

	"github.com/monsterxx03/tachi/config"
	"github.com/monsterxx03/tachi/llm"
	"github.com/monsterxx03/tachi/pkg/debuglog"
)

// ---- Public types ----

// SubagentRunner executes sub-agent tasks for research.
// The engine delegates all search+extraction work to sub-agents.
type SubagentRunner interface {
	Run(ctx context.Context, prompt string, allowedTools []string) (string, error)
}

// DeepResearch is the config-driven deep research engine.
// It does NOT implement the Tool interface — it is used by slash command
// handlers across TUI, Channel, and ACP modes.
type DeepResearch struct {
	cfg             *config.DeepResearchConfig
	providersCfg    []config.ProviderConfig
	defaultProvider llm.Provider
	runner          SubagentRunner
	logger          *debuglog.Logger

	// providerCache caches named providers to avoid re-creating them on each
	// call to getProvider. The default provider is NOT cached here since it
	// is owned by the caller.
	providerCache map[string]llm.Provider
}

// New creates a DeepResearch engine.
//
//   - cfg: DeepResearch configuration (from config.yaml deep_research section)
//   - providersCfg: the full list of provider configs, used to resolve
//     provider references by name (e.g. query_generator_provider)
//   - defaultProvider: fallback LLM provider when a named provider is not found
//   - runner: used to execute sub-agent research tasks
//   - logger: optional logger for debug output
func New(
	cfg *config.DeepResearchConfig,
	providersCfg []config.ProviderConfig,
	defaultProvider llm.Provider,
	runner SubagentRunner,
	logger *debuglog.Logger,
) *DeepResearch {
	return &DeepResearch{
		cfg:             cfg,
		providersCfg:    providersCfg,
		defaultProvider: defaultProvider,
		runner:          runner,
		logger:          logger,
		providerCache:   make(map[string]llm.Provider),
	}
}

// Run executes deep research on the given topic and returns a Markdown report.
// The caller supplies the initial depth and breadth (which are clamped to
// the configured max values).
func (dr *DeepResearch) Run(ctx context.Context, topic string, depth, breadth int) (string, error) {
	// Clamp to configured limits
	if depth > dr.cfg.MaxDepth {
		depth = dr.cfg.MaxDepth
	}
	if breadth > dr.cfg.MaxBreadth {
		breadth = dr.cfg.MaxBreadth
	}
	if breadth < 1 {
		breadth = 1
	}

	// Apply global timeout
	ctx, cancel := context.WithTimeout(ctx, dr.cfg.Timeout)
	defer cancel()

	dr.log("DeepResearch: starting topic=%q depth=%d breadth=%d", topic, depth, breadth)

	allLearnings, allURLs, err := dr.deepResearch(ctx, topic, depth, breadth, nil)
	if err != nil {
		if ctx.Err() != nil {
			dr.log("DeepResearch: timed out or cancelled after %v, generating partial report", dr.cfg.Timeout)
			return dr.buildPartialReport(topic, allLearnings, allURLs, ctx.Err()), nil
		}
		return "", err
	}

	dr.log("DeepResearch: research complete, writing report (learnings=%d, urls=%d)", len(allLearnings), len(allURLs))

	report, err := dr.writeReport(ctx, topic, allLearnings, allURLs)
	if err != nil {
		dr.log("DeepResearch: report writing failed: %v, returning partial results", err)
		return dr.buildPartialReport(topic, allLearnings, allURLs, nil), nil
	}
	return report, nil
}

// ---- Private types ----

// searchQuery is a single search query with its research goal, generated by the LLM.
type searchQuery struct {
	Query        string `json:"query"`
	ResearchGoal string `json:"researchGoal"`
}

// ---- Private methods ----

// deepResearch is the recursive research algorithm.
// It generates queries, launches parallel sub-agents, collects results,
// and optionally recurses with halved breadth.
//
// contextLearnings contains learnings from previous recursion levels,
// used as context for generating the next level's search queries.
// Returns the combined learnings and URLs from this level and all
// deeper levels.
func (dr *DeepResearch) deepResearch(
	ctx context.Context,
	query string,
	depth, breadth int,
	contextLearnings []string,
) (learnings []string, urls []string, err error) {
	select {
	case <-ctx.Done():
		return nil, nil, ctx.Err()
	default:
	}

	// 1. Generate search queries via direct LLM call
	dr.log("DeepResearch: generating %d queries for depth=%d", breadth, depth)
	queries, err := dr.generateQueries(ctx, query, contextLearnings, breadth)
	if err != nil {
		return nil, nil, fmt.Errorf("generate queries: %w", err)
	}
	if len(queries) == 0 {
		dr.log("DeepResearch: no queries generated, stopping recursion")
		return nil, nil, nil
	}

	// 2. Launch parallel sub-agents for each query
	type agentResult struct {
		learnings []string
		urls      []string
		err       error
	}

	results := make([]agentResult, len(queries))
	var mu sync.Mutex
	var wg sync.WaitGroup

	researcherTools := dr.cfg.ResearcherTools()

	for i, sq := range queries {
		wg.Add(1)
		go func(idx int, sq searchQuery) {
			defer wg.Done()
			select {
			case <-ctx.Done():
				mu.Lock()
				results[idx].err = ctx.Err()
				mu.Unlock()
				return
			default:
			}

			prompt := dr.buildResearcherPrompt(sq.Query, sq.ResearchGoal)

			dr.log("DeepResearch: launching sub-agent %d/%d: query=%q", idx+1, len(queries), sq.Query)

			output, runErr := dr.runner.Run(ctx, prompt, researcherTools)
			if runErr != nil {
				mu.Lock()
				results[idx].err = runErr
				mu.Unlock()
				dr.log("DeepResearch: sub-agent %d failed: %v", idx+1, runErr)
				return
			}

			lrnd, urls := extractLearningsAndURLs(output)
			mu.Lock()
			results[idx].learnings = lrnd
			results[idx].urls = urls
			mu.Unlock()
			dr.log("DeepResearch: sub-agent %d complete: %d learnings, %d urls", idx+1, len(lrnd), len(urls))
		}(i, sq)
	}
	wg.Wait()

	// 3. Collect results
	var allLearnings []string
	var allURLs []string
	hasNewLearnings := false
	for _, r := range results {
		if r.err != nil {
			continue
		}
		if len(r.learnings) > 0 {
			hasNewLearnings = true
		}
		allLearnings = append(allLearnings, r.learnings...)
		allURLs = append(allURLs, r.urls...)
	}

	// Check max learnings limit
	if len(allLearnings) >= dr.cfg.MaxLearnings {
		allLearnings = allLearnings[:dr.cfg.MaxLearnings]
		dr.log("DeepResearch: reached max learnings (%d), stopping", dr.cfg.MaxLearnings)
		return allLearnings, allURLs, nil
	}

	// 4. Recurse if depth > 0 and we have new learnings
	if depth > 0 && hasNewLearnings {
		nextBreadth := breadth / 2
		if nextBreadth < 1 {
			nextBreadth = 1
		}
		dr.log("DeepResearch: recursing with depth=%d breadth=%d", depth-1, nextBreadth)

		// Pass accumulated learnings as context for next-level query generation
		nextLearnings, nextURLs, recurseErr := dr.deepResearch(ctx, query, depth-1, nextBreadth, allLearnings)
		if recurseErr != nil {
			return allLearnings, allURLs, recurseErr
		}

		// Merge deeper-level results
		allLearnings = append(allLearnings, nextLearnings...)
		allURLs = append(allURLs, nextURLs...)
		if len(allLearnings) > dr.cfg.MaxLearnings {
			allLearnings = allLearnings[:dr.cfg.MaxLearnings]
		}
	}

	if depth > 0 && !hasNewLearnings {
		dr.log("DeepResearch: no new learnings found, stopping recursion")
	}

	return allLearnings, allURLs, nil
}

// generateQueries calls the LLM to generate search queries for the current
// research level. The LLM response must be a JSON array of searchQuery objects.
func (dr *DeepResearch) generateQueries(
	ctx context.Context,
	query string,
	learnings []string,
	num int,
) ([]searchQuery, error) {
	provider, err := dr.getProvider(dr.cfg.QueryGeneratorProvider)
	if err != nil {
		return nil, fmt.Errorf("get provider for query generation: %w", err)
	}

	// Build prompt from template
	promptTmpl := dr.cfg.QueryGeneratorPrompt()

	learningsText := ""
	if len(learnings) > 0 {
		learningsText = strings.Join(learnings, "\n- ")
		if learningsText != "" {
			learningsText = "- " + learningsText
		}
	}

	systemPrompt := strings.NewReplacer(
		"{breadth}", fmt.Sprintf("%d", num),
		"{query}", query,
		"{learnings}", learningsText,
	).Replace(promptTmpl)

	messages := []llm.Message{
		{Role: "system", Content: systemPrompt},
		{Role: "user", Content: fmt.Sprintf("Generate %d search queries for: %s", num, query)},
	}

	disabled := false
	resp, err := provider.CreateChat(ctx, messages, nil, llm.ChatOptions{
		MaxTokens: 2048,
		Thinking:  &disabled,
	})
	if err != nil {
		return nil, fmt.Errorf("LLM query generation failed: %w", err)
	}

	// Parse JSON from response (may be wrapped in markdown code blocks)
	jsonStr := extractJSONArray(resp.Content)
	if jsonStr == "" {
		return nil, fmt.Errorf("LLM did not return valid JSON array of queries")
	}

	var queries []searchQuery
	if err := json.Unmarshal([]byte(jsonStr), &queries); err != nil {
		return nil, fmt.Errorf("parse queries JSON: %w\nRaw: %s", err, truncateText(jsonStr, 200))
	}

	if len(queries) == 0 {
		return nil, nil
	}

	// Clamp to requested number
	if len(queries) > num {
		queries = queries[:num]
	}

	return queries, nil
}

// buildResearcherPrompt builds the prompt for a research sub-agent.
func (dr *DeepResearch) buildResearcherPrompt(query, researchGoal string) string {
	return strings.NewReplacer(
		"{query}", query,
		"{researchGoal}", researchGoal,
	).Replace(dr.cfg.ResearcherPrompt())
}

// writeReport generates the final research report.
//
// Two modes (controlled by config.ReportWriterMode()):
//   - "subagent":   Delegates report writing to a SubAgent (uses the runner).
//   - "direct_llm": Uses a direct LLM call (cheaper, uses the configured or
//     default provider).
func (dr *DeepResearch) writeReport(
	ctx context.Context,
	topic string,
	learnings []string,
	urls []string,
) (string, error) {
	if len(learnings) == 0 {
		return dr.buildPartialReport(topic, learnings, urls, nil), nil
	}

	mode := dr.cfg.ReportWriterMode()

	switch mode {
	case "direct_llm":
		return dr.writeReportDirect(ctx, topic, learnings, urls)
	default:
		return dr.writeReportViaSubagent(ctx, topic, learnings, urls)
	}
}

// writeReportViaSubagent delegates report writing to a sub-agent.
func (dr *DeepResearch) writeReportViaSubagent(
	ctx context.Context,
	topic string,
	learnings []string,
	urls []string,
) (string, error) {
	prompt := dr.buildReportWriterPrompt(topic, learnings, urls)

	dr.log("DeepResearch: writing report via sub-agent")
	output, err := dr.runner.Run(ctx, prompt, dr.cfg.ResearcherTools())
	if err != nil {
		return "", fmt.Errorf("report sub-agent: %w", err)
	}
	return output, nil
}

// writeReportDirect writes the report via a direct LLM call.
func (dr *DeepResearch) writeReportDirect(
	ctx context.Context,
	topic string,
	learnings []string,
	urls []string,
) (string, error) {
	providerName := dr.cfg.ReportWriterProvider()
	provider, err := dr.getProvider(providerName)
	if err != nil {
		return "", fmt.Errorf("get provider for report writing: %w", err)
	}

	prompt := dr.buildReportWriterPrompt(topic, learnings, urls)

	messages := []llm.Message{
		{Role: "system", Content: "You are a research report writer. Write comprehensive Markdown reports."},
		{Role: "user", Content: prompt},
	}

	disabled := false
	resp, err := provider.CreateChat(ctx, messages, nil, llm.ChatOptions{
		MaxTokens: 8192,
		Thinking:  &disabled,
	})
	if err != nil {
		return "", fmt.Errorf("LLM report writing failed: %w", err)
	}

	return resp.Content, nil
}

// buildReportWriterPrompt builds the prompt for the report writer.
func (dr *DeepResearch) buildReportWriterPrompt(topic string, learnings []string, urls []string) string {
	learningsText := strings.Join(learnings, "\n\n---\n\n")
	urlsText := strings.Join(urls, "\n")

	promptTmpl := dr.cfg.ReportWriterPrompt()
	return strings.NewReplacer(
		"{query}", topic,
		"{learnings}", learningsText,
		"{urls}", urlsText,
	).Replace(promptTmpl)
}

// buildPartialReport builds a simple report from whatever learnings were
// collected, even if the research was interrupted.
func (dr *DeepResearch) buildPartialReport(topic string, learnings []string, urls []string, err error) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Deep Research Report: %s\n\n", topic))

	if err != nil {
		sb.WriteString(fmt.Sprintf("> ⚠️ Research was interrupted: %v\n\n", err))
	}

	if len(learnings) == 0 {
		sb.WriteString("No findings were collected.\n")
		return sb.String()
	}

	sb.WriteString("## Findings\n\n")
	for i, l := range learnings {
		sb.WriteString(fmt.Sprintf("### Finding %d\n\n%s\n\n", i+1, l))
	}

	if len(urls) > 0 {
		sb.WriteString("## Sources\n\n")
		seen := make(map[string]bool)
		for _, u := range urls {
			u = strings.TrimSpace(u)
			if u == "" || seen[u] {
				continue
			}
			seen[u] = true
			sb.WriteString(fmt.Sprintf("- %s\n", u))
		}
	}

	return sb.String()
}

// getProvider resolves a provider by name from the providers config list.
// Named providers are cached to avoid re-creating them on each call.
// If name is empty or not found, falls back to the default provider.
func (dr *DeepResearch) getProvider(name string) (llm.Provider, error) {
	if name == "" {
		if dr.defaultProvider != nil {
			return dr.defaultProvider, nil
		}
		return nil, fmt.Errorf("no provider name specified and no default provider available")
	}

	// Check cache first
	if p, ok := dr.providerCache[name]; ok {
		return p, nil
	}

	for _, p := range dr.providersCfg {
		if p.Name == name {
			resolved, err := config.ResolveProviderConfig(&p)
			if err != nil {
				return nil, fmt.Errorf("resolve provider %q: %w", name, err)
			}
			provider, err := llm.NewProvider(resolved.Type, resolved.APIKey, resolved.BaseURL, resolved.Model)
			if err != nil {
				return nil, fmt.Errorf("create provider %q: %w", name, err)
			}
			dr.providerCache[name] = provider
			return provider, nil
		}
	}

	// Not found — fall back to default
	if dr.defaultProvider != nil {
		dr.log("DeepResearch: provider %q not found in config, falling back to default", name)
		return dr.defaultProvider, nil
	}
	return nil, fmt.Errorf("provider %q not found and no default available", name)
}

// log writes a debug log message if the logger is configured.
func (dr *DeepResearch) log(format string, args ...any) {
	if dr.logger != nil {
		dr.logger.Log(format, args...)
	}
}

// ---- Helper functions ----

// urlRegex matches URLs for extraction from sub-agent output.
// Uses \x60 to match backtick within the raw string literal.
var urlRegex = regexp.MustCompile(`https?://[^\s\)\]}>"'\x60]+`)

// extractLearningsAndURLs extracts learnings and URLs from a sub-agent's output.
// It treats the full output as learning content, and extracts URLs separately.
func extractLearningsAndURLs(output string) (learnings []string, urls []string) {
	if output == "" {
		return nil, nil
	}

	// Use the full output as a single learning
	learnings = append(learnings, strings.TrimSpace(output))

	// Extract URLs
	matches := urlRegex.FindAllString(output, -1)
	seen := make(map[string]bool)
	for _, u := range matches {
		u = strings.TrimRight(u, ".,;:!?")
		if !seen[u] {
			urls = append(urls, u)
			seen[u] = true
		}
	}

	return learnings, urls
}

// extractJSONArray extracts a JSON array from an LLM response.
// Handles responses wrapped in markdown code blocks (```json ... ```).
func extractJSONArray(input string) string {
	input = strings.TrimSpace(input)

	// Try to find a JSON array inside markdown code blocks
	if idx := strings.Index(input, "```"); idx >= 0 {
		rest := input[idx+3:]
		// Skip optional "json" language marker
		rest = strings.TrimPrefix(rest, "json")
		rest = strings.TrimSpace(rest)

		if endIdx := strings.Index(rest, "```"); endIdx >= 0 {
			content := strings.TrimSpace(rest[:endIdx])
			if strings.HasPrefix(content, "[") {
				return content
			}
		}
	}

	// No code block — try to find array directly
	if idx := strings.Index(input, "["); idx >= 0 {
		// Find matching closing bracket
		depth := 0
		for i := idx; i < len(input); i++ {
			switch input[i] {
			case '[':
				depth++
			case ']':
				depth--
				if depth == 0 {
					return input[idx : i+1]
				}
			}
		}
	}

	return ""
}

// truncateText truncates a string to the given length with an ellipsis.
func truncateText(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}
