// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Question represents a single question to ask the user
 */
export interface Question {
    "question": string;
    "header": string;
    "options": QuestionOption[] | null;
    "multi_select": boolean;
}

/**
 * QuestionOption represents a single option in a question
 */
export interface QuestionOption {
    "label": string;
    "description": string;
    "preview"?: string;
}
