package manager

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/monsterxx03/tachi/agent"
	"github.com/monsterxx03/tachi/agent/transcript/render"
	"github.com/monsterxx03/tachi/llm"
	"github.com/monsterxx03/tachi/pkg/channel"
	"github.com/monsterxx03/tachi/session"
)

// --- /compact ---

// finalizeCompactResult creates a new session with the LLM-generated summary,
// links it bidirectionally to the old session, migrates the ThreadID, and
// returns a formatted result string for the channel response.
//
// Unlike the old handleCompactCommand, this does NOT run the LLM call itself —
// the summary has already been generated by runAgentTurn using the current
// session context (no history re-embedding).
//
// aiAgent supplies the memory backend for the pre-compaction write; it may be
// nil, in which case the session is finalized without a memory write.
func (m *Manager) finalizeCompactResult(threadID string, summary string, aiAgent *agent.AIAgent) (string, error) {
	sm := m.newSessionManager()
	sess, err := sm.FindByThreadID(threadID)
	if err != nil {
		return "", fmt.Errorf("加载 session 失败: %w", err)
	}
	if sess == nil || !sm.HasCurrent() {
		return "没有活跃的会话可以压缩。请先发送消息开始对话。", nil
	}

	sessionMsgs, err := sm.LoadMessages()
	if err != nil {
		return "", fmt.Errorf("加载消息失败: %w", err)
	}

	// Finalize: create new session, write summary, link old ↔ new.
	sid := ""
	if cur := sm.Current(); cur != nil {
		sid = cur.ID
	}
	systemPrompt := agent.BuildSystemPrompt(m.cfg.Language, "", sid)
	if aiAgent != nil {
		_, err = aiAgent.CompleteCompact(sm, systemPrompt, summary)
	} else {
		_, err = agent.FinalizeCompact(sm, systemPrompt, summary)
	}
	if err != nil {
		return "", fmt.Errorf("创建压缩会话失败: %w", err)
	}
	// ThreadID migration is handled inside FinalizeCompact: the new session
	// inherits the binding and the old session releases it.

	return fmt.Sprintf(
		"🔍 对话已压缩\n\n原会话: %s (%s)\n消息数: %d\n\n摘要:\n%s",
		sess.Title, sess.ID[:8], len(sessionMsgs), summary,
	), nil
}

// --- /transcript ---

// handleTranscriptCommand generates an HTML transcript for the session
// associated with the given thread and returns it as a file attachment.
//
// Called from executeSlashCommand for the "transcript" case.
//
// Args:
//   - threadID: the thread whose session to render (or "" if using --latest)
//   - args: command arguments (e.g. "--latest")
func (m *Manager) handleTranscriptCommand(threadID, args string) channel.HandlerResult {
	errReply := func(err error) channel.HandlerResult {
		return channel.HandlerResult{
			Reply: channel.OutgoingMessage{
				ThreadID: threadID,
				Content:  fmt.Sprintf("❌ %v", err),
			},
			Err: err,
		}
	}

	sm := m.newSessionManager()
	if sm == nil {
		return errReply(fmt.Errorf("session manager unavailable"))
	}

	var sess *session.Session
	var err error

	parts := strings.Fields(args)
	useLatest := len(parts) > 0 && parts[0] == "--latest"

	if useLatest {
		sessions, listErr := sm.List()
		if listErr != nil {
			return errReply(fmt.Errorf("list sessions: %w", listErr))
		}
		if len(sessions) == 0 {
			return errReply(fmt.Errorf("no sessions found"))
		}
		sess, err = sm.Load(sessions[0].ID)
		if err != nil {
			return errReply(fmt.Errorf("load session: %w", err))
		}
	} else {
		found, findErr := sm.FindByThreadID(threadID)
		if findErr != nil {
			return errReply(fmt.Errorf("find session: %w", findErr))
		}
		if found == nil {
			return errReply(fmt.Errorf("no session found for this thread; send a message first to start a session"))
		}
		sess = found
	}

	msgs, err := sm.LoadMessages()
	if err != nil {
		return errReply(fmt.Errorf("load messages: %w", err))
	}
	if len(msgs) == 0 {
		return errReply(fmt.Errorf("session %q has no messages yet; run a conversation first", sess.ID))
	}

	// Sub-agent sidecar messages are optional — a load failure is non-fatal.
	subagents, _ := sm.LoadSubagentMessages(sess.ID)

	data := render.BuildReportDataFromMessages(sess, msgs, subagents)
	html, err := render.GenerateHTML(data)
	if err != nil {
		return errReply(fmt.Errorf("generate HTML: %w", err))
	}

	// Use session title as filename, sanitized.
	fileName := sanitizeFilename(sess.Title)
	if fileName == "" {
		fileName = "transcript"
	}
	htmlFileName := fmt.Sprintf("%s-%s.html", fileName, sess.ID[:8])

	m.logger.Info(context.Background(), "channel: transcript generated", "id", sess.ID, "bytes", len(html))

	contentText := fmt.Sprintf("📊 Transcript: %s\n\nSession: %s\nTurns: %d · Tools: %d · Size: %s",
		sess.Title, sess.ID[:8],
		data.Stats.TurnCount, data.Stats.ToolCallCount, humanSize(len(html)))

	return channel.HandlerResult{
		Reply: channel.OutgoingMessage{
			Content:  contentText,
			ThreadID: threadID,
			Attachments: []channel.OutgoingAttachment{
				{
					Type:     channel.AttachmentTypeFile,
					FileName: htmlFileName,
					MimeType: "text/html",
					Data:     []byte(html),
				},
			},
		},
	}
}

// --- /research ---

// handleResearchCommand runs deep research on the given topic, synchronously
// (the channel goroutine blocks while research is in progress; progress goes
// to the thread via sendToThread). Holds the thread's agent lock for the
// duration, preventing concurrent messages on the same thread.
func (m *Manager) handleResearchCommand(threadID, args string) (string, error) {
	if m.cfg == nil {
		return "", fmt.Errorf("manager config unavailable")
	}

	ca, err := m.acquireAgent(context.Background(), threadID)
	if err != nil {
		return "", fmt.Errorf("acquire agent: %w", err)
	}
	defer m.releaseAgent(ca)

	// Ensure the thread has a session before running: the first message on a
	// thread may be /research itself, and runAgentTurn's
	// prepareThreadSession — which normally creates the session and wires
	// the SessionManager — never runs for slash commands. Without it, the
	// artifact registration below would find no session.
	resolved := m.getProviderForThread(threadID)
	if sm, _ := m.prepareThreadSession(threadID, resolved); sm != nil {
		ca.agent.SetSessionManager(sm)
	}

	report, artifact, err := ca.agent.RunDeepResearch(context.Background(), m.cfg, args,
		// Initial progress message with the resolved parameters.
		func(topic string, depth, breadth int) {
			m.sendToThread(context.Background(), threadID,
				fmt.Sprintf("🔬 **深度研究已启动**\n\n**主题**: %s\n**深度**: %d | **广度**: %d\n\n正在搜索中...",
					topic, depth, breadth), "")
		},
		// Progress callbacks stream intermediate updates to the thread.
		func(text string) {
			m.sendToThread(context.Background(), threadID, text, "")
		})
	if errors.Is(err, agent.ErrResearchUsage) {
		return "Usage: `/research <topic> [--depth N] [--breadth N]`", nil
	}
	if errors.Is(err, agent.ErrResearchUnavailable) {
		return "Deep Research is not available (engine creation returned nil).", nil
	}
	if err != nil {
		return "", err
	}

	// Splice the artifact reminder into the thread's in-memory cache:
	// RunDeepResearch wrote it to disk, but the next turn's LLM input comes
	// from ca.history while the cached agent is alive.
	if artifact != nil {
		m.spliceArtifactIntoCache(ca, *artifact)
	}
	return report, nil
}

// spliceArtifactIntoCache appends an artifact reminder to a thread's cached
// in-memory history so the next turn sees it. No-op when the cache is nil
// (first turn / after eviction — the disk reload path handles it). Caller
// must hold the cached agent's lock.
func (m *Manager) spliceArtifactIntoCache(ca *cachedAgent, ref session.ArtifactRef) {
	if ca == nil || ca.history == nil {
		return
	}
	ca.history = append(ca.history, llm.Message{
		Role:    "user",
		Content: session.FormatArtifactReminder([]session.ArtifactRef{ref}),
	})
}

// --- /restart ---

// handleRestartCommand checks if Tachi is running under systemd and restarts
// the service via systemctl. Returns an error if not running under systemd.
// It sends a proactive "restarting" message before executing the restart.
func (m *Manager) handleRestartCommand(threadID string) (string, error) {
	// Check if running under systemd by verifying PPID == 1 and
	// /proc/1/comm is "systemd". This works on all systemd versions,
	// unlike INVOCATION_ID which requires systemd >= 232 (CentOS 7 has v219).
	if !isRunningUnderSystemd() {
		return "", errors.New("tachi 不是由 systemd 启动的，无法通过 systemctl 重启")
	}

	// Determine if this is a user service or system service.
	// User services have XDG_RUNTIME_DIR set.
	_, isUser := os.LookupEnv("XDG_RUNTIME_DIR")

	// Build the systemctl command.
	args := []string{}
	if isUser {
		args = append(args, "--user")
	}
	args = append(args, "restart", "tachi")

	// Send a proactive reply BEFORE executing the restart, so the user
	// actually sees the message before systemd kills this process.
	m.sendToThread(context.Background(), threadID,
		"🔄 正在重启 Tachi...\n\n```\nsystemctl "+strings.Join(args, " ")+"\n```", "")

	// Execute asynchronously — we don't wait for the process to exit
	// because the systemd stop signal will kill us first.
	cmd := exec.Command("systemctl", args...)
	cmd.Stdout = nil
	cmd.Stderr = nil

	if err := cmd.Start(); err != nil {
		return "", fmt.Errorf("启动 systemctl 失败: %w", err)
	}

	// Return an empty message — the real reply was already sent via
	// sendToThread above. Returning empty tells the caller not to send
	// a duplicate.
	return "", nil
}

// isRunningUnderSystemd checks if the current process is managed by systemd.
// It verifies that the parent process (PPID 1) is systemd, which works on all
// systemd versions including older ones like systemd 219 on CentOS 7.
func isRunningUnderSystemd() bool {
	data, err := os.ReadFile("/proc/1/comm")
	if err != nil {
		return false
	}
	return string(data) == "systemd\n"
}
