// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * ModelSpec 汇总模型级运行时属性：上下文窗口、定价、思考级别、请求行为。
 * 通过 ProviderConfig.Spec 嵌套配置（不向前兼容旧版平铺字段）。
 */
export interface ModelSpec {
    /**
     * ContextWindow 手动覆盖模型上下文窗口（tokens）。
     */
    "ContextWindow": number | null;

    /**
     * ThinkingLevel 控制思考模式强度。不同模型支持不同级别：
     *   - "none"             关闭思考模式
     *   - "low"/"medium"/"high"/"xhigh"/"max"  设置思考强度
     * 空 = 使用模型内置默认（DeepSeek: 思考开启、effort high；Anthropic: adaptive）。
     * 请求的级别会原样透传给 API，由服务端映射到模型实际的推理强度
     * （如 DeepSeek thinking_mode 文档的 effort 映射表）。
     */
    "ThinkingLevel": string;

    /**
     * Vision 标记模型是否支持图片（多模态）输入。
     *   - nil（默认）：按模型名内置能力表自动判断（llm.ModelSupportsVision）
     *   - true：显式声明支持图片
     *   - false：显式声明不支持图片（即使模型名命中了能力表）
     * 当当前模型不支持图片但输入包含图片时，Tachi 会调用配置中第一个
     * 支持图片的 provider 描述图片，再把描述文本喂给当前模型。
     */
    "Vision": boolean | null;

    /**
     * MaxRetries 失败后的额外重试次数。nil = 使用默认（各 provider 路径均为
     * 2 次）；0 = 禁用重试；n = 重试 n 次。
     * 落地方式：openai（go-openai，无内置重试）走外层 RetryProvider；
     * anthropic / openai-res 走 SDK 内置重试（option.WithMaxRetries）。
     */
    "MaxRetries": number | null;

    /**
     * Timeout 单次 LLM API 请求超时。0 = 使用默认（各路径不设超时）。
     * 落地方式：openai（go-openai）设置 HTTP client 超时；
     * anthropic / openai-res 走 SDK 的 option.WithRequestTimeout。
     */
    "Timeout": time$0.Duration;

    /**
     * Pricing 定价覆盖（可选，覆盖内置价格表）。类型定义在本包
     * （PricingConfig）——定价 schema 单一来源，config 只负责装载，
     * 定价语义（内置表/分时带）由 llm 解析。
     */
    "Pricing": PricingConfig | null;

    /**
     * CreditRate 配置 credit 计算的速率（每 unitDivisor 个 token 的 credit
     * 单价，见 llm.ComputeCredit）。nil/未配置 = 0（不产生 credit）。
     * 计算时优先用账本行内记录的调用时刻快照；升级前的历史行没有快照，
     * 聚合展示时用此处配置的当前 rate 实时回算。
     */
    "CreditRate": number | null;
}

/**
 * PriceBandSpec is one raw time-of-use band in user-facing form: Start/End
 * are "HH:MM" (24h, inclusive start, exclusive end; end <= start wraps past
 * midnight, end == start = whole day; minutes must be 0). nil price fields
 * inherit the flat price, explicit 0 = free.
 * Days restricts the band to a subset of the week (1 = Monday … 7 = Sunday);
 * empty = every day. Days with a band miss the weekday → the flat price
 * applies (e.g. a workday-only peak band leaves weekends fully off-peak).
 */
export interface PriceBandSpec {
    /**
     * band name written to the ledger row ("" = unnamed)
     */
    "Name": string;

    /**
     * 1=周一 … 7=周日；空 = 每天
     */
    "Days": number[] | null;
    "Start": string;
    "End": string;
    "InputPrice": number | null;
    "OutputPrice": number | null;
    "CacheReadInputPrice": number | null;
    "CacheCreationInputPrice": number | null;
}

/**
 * PricingConfig is the user-facing per-provider pricing override block (the
 * SAME type as the resolver — one source of truth for the pricing schema,
 * no translation layer. The yaml tags are consumed by this package's YAML
 * loading; the pricing semantics (built-in table, versioning, band
 * inheritance, time pinning) live in llm.
 * 
 * All fields are optional: nil = not set (flat prices fall back to the
 * built-in table; band fields inherit the flat price), explicit 0 = free.
 * Timezone anchors band selection (IANA name, e.g. "Asia/Shanghai");
 * empty = the instant's own local timezone.
 */
export interface PricingConfig {
    "InputPrice": number | null;
    "OutputPrice": number | null;
    "CacheReadInputPrice": number | null;
    "CacheCreationInputPrice": number | null;
    "Timezone": string;
    "Bands": PriceBandSpec[] | null;
}

export interface ProviderConfig {
    "Name": string;
    "Type": string;
    "Model": string;
    "BaseURL": string;
    "APIKey": string;
    "Spec": ModelSpec;
}
