package main

import (
	"context"
	"embed"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/wailsapp/wails/v3/pkg/application"
	"github.com/wailsapp/wails/v3/pkg/events"
)

// Window background colours, mirroring --bg in base.css (light / dark). The
// window is opaque, so this is what shows for the instant before the frontend
// paints — it has to follow the theme, or a dark desktop gets a white flash on
// launch.
var (
	windowBgLight = application.NewRGB(0xf6, 0xf7, 0xfb)
	windowBgDark  = application.NewRGB(0x21, 0x24, 0x29)
)

// forcedAppearance reads TACHI_DESKTOP_APPEARANCE ("dark" / "light") and maps
// it to a Cocoa appearance, or returns DefaultAppearance to follow the system.
// Dev aid: it makes the dark theme inspectable without flipping the appearance
// of the whole machine.
func forcedAppearance() application.MacAppearanceType {
	switch strings.ToLower(os.Getenv("TACHI_DESKTOP_APPEARANCE")) {
	case "dark":
		return application.NSAppearanceNameDarkAqua
	case "light":
		return application.NSAppearanceNameAqua
	default:
		return application.DefaultAppearance
	}
}

// Assets embeds the built frontend. It is regenerated by `wails3 build` from
// `frontend/dist`; the embed pattern fails to compile until the frontend has
// been built once (same caveat as the tachi web console).
//
//go:embed all:frontend/dist
var assets embed.FS

func init() {
	// Register the custom event so the binding generator emits a strongly
	// typed JS/TS API for it. The payload is the agent state snapshot.
	application.RegisterEvent[AgentState]("agent:state")
	// Native file drops: the payload carries the dropped paths (see
	// desktop/fileservice.go).
	application.RegisterEvent[FileDropEvent]("agent:filedrop")
}

// assetHandler serves the embedded frontend assets, and additionally answers
// `/local?p=<abs path>` by serving a local file from disk — this lets `<img>`
// tags in AI markdown replies render local images (e.g. screenshots) that the
// webview otherwise cannot load by path.
func assetHandler(assets embed.FS) http.Handler {
	embedHandler := application.AssetFileServerFS(assets)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/local" {
			p := r.URL.Query().Get("p")
			if p != "" {
				http.ServeFile(w, r, p)
				return
			}
		}
		embedHandler.ServeHTTP(w, r)
	})
}

func main() {
	desk := newDesktopApp()

	app := application.New(application.Options{
		Name:        "Tachi",
		Description: "Tachi — AI Agent desktop companion",
		Services: []application.Service{
			application.NewService(&AgentService{desk: desk}),
		},
		Assets: application.AssetOptions{
			Handler: assetHandler(assets),
		},
		Mac: application.MacOptions{
			// Keep the app alive in the menu bar when the window closes.
			ApplicationShouldTerminateAfterLastWindowClosed: false,
		},
	})

	// Appearance: follow the system by default (the frontend's
	// prefers-color-scheme rides on the same Cocoa appearance), or take a
	// forced value from TACHI_DESKTOP_APPEARANCE.
	appearance := forcedAppearance()
	dark := appearance == application.NSAppearanceNameDarkAqua ||
		(appearance == application.DefaultAppearance && app.Env.IsDarkMode())
	background := windowBgLight
	if dark {
		background = windowBgDark
	}

	// Main conversational window.
	// Native macOS title bar is hidden but its traffic-light buttons remain
	// (like Zed): MacTitleBarHidden keeps the standard red/yellow/green controls
	// in the top-left while the content fills the window. InvisibleTitleBarHeight
	// gives the top region a drag handle.
	window := app.Window.NewWithOptions(application.WebviewWindowOptions{
		Title:     "Tachi",
		Width:     1200,
		Height:    780,
		MinWidth:  900,
		MinHeight: 600,
		Mac: application.MacWindow{
			InvisibleTitleBarHeight: 44,
			// Opaque window: the UI is a flat, solid design (no vibrancy, no
			// backdrop blur anywhere), so the desktop behind the window must
			// not bleed through.
			Backdrop: application.MacBackdropNormal,
			TitleBar: application.MacTitleBarHidden,
			// DefaultAppearance lets the webview follow the system theme.
			Appearance: appearance,
		},
		// Matches --bg in base.css for the current theme, so the window never
		// flashes a different shade before the frontend paints.
		BackgroundColour: background,
		// Native drag-and-drop of files onto the window. Drops only register
		// on elements marked data-file-drop-target (the composer), and the
		// webview cannot read the paths itself — they arrive in Go via the
		// WindowFilesDropped event below and are forwarded to the frontend.
		EnableFileDrop: true,
		URL:            "/",
	})
	desk.app = app
	desk.window = window

	// Forward native file drops to the frontend, which inserts @-references
	// into the input area. The element id lets the frontend decide where the
	// drop landed (and ignore drops outside the drop targets).
	window.OnWindowEvent(events.Common.WindowFilesDropped, func(e *application.WindowEvent) {
		elementID := ""
		if dt := e.Context().DropTargetDetails(); dt != nil {
			elementID = dt.ElementID
		}
		desk.emitFileDrop(e.Context().DroppedFiles(), elementID)
	})

	// Keep that background in step with the system when it changes under us
	// (the frontend follows prefers-color-scheme itself; this covers the
	// pre-paint flash and the frame around the webview).
	if appearance == application.DefaultAppearance {
		app.Event.OnApplicationEvent(events.Mac.ApplicationDidChangeTheme, func(*application.ApplicationEvent) {
			colour := windowBgLight
			if app.Env.IsDarkMode() {
				colour = windowBgDark
			}
			window.SetBackgroundColour(colour)
		})
	}

	// Menu bar item reflecting the agent state.
	desk.tray = setupTray(desk)

	// Initial state broadcast (drives tray label/icon + frontend status bar).
	desk.setSessionState("", AgentState{Status: StatusIdle, Label: "空闲", Detail: "就绪"})

	// Boot the real tachi agent (falls back to simulated turns on failure).
	if err := desk.initAgent(context.Background()); err != nil {
		log.Printf("agent unavailable, falling back to simulated turns: %v", err)
		desk.setSessionState("", AgentState{Status: StatusIdle, Label: "空闲", Detail: "未配置 agent（模拟模式）"})
	}

	// Optional self-test driver (TACHI_DEMO): inject JS to type & send from
	// within the webview, so we can exercise input + state transitions without
	// relying on system-level mouse/keyboard coordinates.
	if demoEnabled() {
		go runJsDemo(window)
	}

	// Run the application.
	if err := app.Run(); err != nil {
		log.Fatal(err)
	}
	desk.teardownAgent()
}
