package main

import (
	"embed"
	"log"

	"github.com/wailsapp/wails/v3/pkg/application"
)

// Assets embeds the built frontend. It is regenerated by `wails3 build` from
// `frontend/dist`; the embed pattern fails to compile until the frontend has
// been built once (same caveat as the tachi web console).
//
//go:embed all:frontend/dist
var assets embed.FS

func init() {
	// Register the custom event so the binding generator emits a strongly
	// typed JS/TS API for it. The payload is the agent state snapshot.
	application.RegisterEvent[AgentState]("agent:state")
}

func main() {
	desk := newDesktopApp()

	app := application.New(application.Options{
		Name:        "tachi-desktop",
		Description: "Tachi — AI Agent desktop companion",
		Services: []application.Service{
			application.NewService(&AgentService{desk: desk}),
		},
		Assets: application.AssetOptions{
			Handler: application.AssetFileServerFS(assets),
		},
		Mac: application.MacOptions{
			// Keep the app alive in the menu bar when the window closes.
			ApplicationShouldTerminateAfterLastWindowClosed: false,
		},
	})

	// Main conversational window.
	// Native macOS title bar is hidden but its traffic-light buttons remain
	// (like Zed): MacTitleBarHidden keeps the standard red/yellow/green controls
	// in the top-left while the content fills the window. InvisibleTitleBarHeight
	// gives the top region a drag handle.
	window := app.Window.NewWithOptions(application.WebviewWindowOptions{
		Title:     "Tachi",
		Width:     1200,
		Height:    780,
		MinWidth:  900,
		MinHeight: 600,
		Mac: application.MacWindow{
			InvisibleTitleBarHeight: 44,
			Backdrop:                application.MacBackdropTranslucent,
			TitleBar:                application.MacTitleBarHidden,
		},
		BackgroundColour: application.NewRGB(245, 246, 250),
		URL:              "/",
	})
	desk.app = app
	desk.window = window

	// Menu bar item reflecting the agent state.
	desk.tray = setupTray(desk)

	// Initial state broadcast (drives tray label/icon + frontend status bar).
	desk.setState(AgentState{Status: StatusIdle, Label: "空闲", Detail: "就绪"})

	// Idle heartbeat so the menu bar always reflects the current state.
	go desk.simulateRuntime()

	// Keep the process alive on clean quit so defers/cleanup can run.
	if err := app.Run(); err != nil {
		log.Fatal(err)
	}
}
