package main

import (
	"context"
	"embed"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/wailsapp/wails/v3/pkg/application"
	"github.com/wailsapp/wails/v3/pkg/events"
)

// Window background colours, mirroring --bg in base.css (light / dark). The
// window is opaque, so this is what shows for the instant before the frontend
// paints — it has to follow the theme, or a dark desktop gets a white flash on
// launch.
var (
	windowBgLight = application.NewRGB(0xf6, 0xf7, 0xfb)
	windowBgDark  = application.NewRGB(0x21, 0x24, 0x29)
)

// forcedAppearance reads TACHI_DESKTOP_APPEARANCE ("dark" / "light") and maps
// it to a Cocoa appearance, or returns DefaultAppearance to follow the system.
// Dev aid: it makes the dark theme inspectable without flipping the appearance
// of the whole machine.
func forcedAppearance() application.MacAppearanceType {
	switch strings.ToLower(os.Getenv("TACHI_DESKTOP_APPEARANCE")) {
	case "dark":
		return application.NSAppearanceNameDarkAqua
	case "light":
		return application.NSAppearanceNameAqua
	default:
		return application.DefaultAppearance
	}
}

// Assets embeds the built frontend. It is regenerated by `wails3 build` from
// `frontend/dist`; the embed pattern fails to compile until the frontend has
// been built once (same caveat as the tachi web console).
//
//go:embed all:frontend/dist
var assets embed.FS

func init() {
	// Register the custom event so the binding generator emits a strongly
	// typed JS/TS API for it. The payload is the agent state snapshot.
	application.RegisterEvent[AgentState]("agent:state")
	// Native file drops: the payload carries the dropped paths (see
	// desktop/fileservice.go).
	application.RegisterEvent[FileDropEvent]("agent:filedrop")
	// AskUserQuestion forms: the payload carries the questions to render (see
	// desktop/askuser.go).
	application.RegisterEvent[AskEvent]("agent:ask")
	// Theme switches from the titlebar: the frontend sends the theme it just
	// applied (see desktop/uitheme.go).
	application.RegisterEvent[string](uiThemeEventName)
}

// localAssetRoute is the prefix the webview uses to reach files on disk (see
// assetHandler).
const localAssetRoute = "/local"

// assetHandler serves the embedded frontend assets, and additionally answers
// local files for the two cases the webview cannot load by path:
//
//	/local?p=<abs path>   — a single file, addressed by query
//	/local/<abs path>     — the same file with the disk path in the URL PATH
//
// The query form is what markdown images use (toLocalAsset). The path form
// exists for the HTML preview: the document loads from /local/.../report.html,
// so its own relative references ("./chart.js", "./style.css") resolve against
// that URL and land back here — under the query form the browser would resolve
// them against the app root and 404.
//
// Both forms serve any path the user can read, which is the desktop app's
// standing trade: the route is only reachable from its own webview, and the
// files being shown are the ones the agent just handed over.
func assetHandler(assets embed.FS) http.Handler {
	embedHandler := application.AssetFileServerFS(assets)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if p := localAssetPath(r); p != "" {
			http.ServeFile(w, r, p)
			return
		}
		embedHandler.ServeHTTP(w, r)
	})
}

// localAssetPath maps a /local request onto a disk path, or returns "" when the
// request is not one (and should fall through to the embedded assets).
func localAssetPath(r *http.Request) string {
	if r.URL.Path == localAssetRoute {
		return r.URL.Query().Get("p")
	}
	rest, ok := strings.CutPrefix(r.URL.Path, localAssetRoute+"/")
	if !ok || rest == "" {
		return ""
	}
	// The URL path is already percent-decoded by net/http, and Clean keeps a
	// ".." segment from climbing out of the absolute path it is joined onto.
	return filepath.Clean("/" + rest)
}

func main() {
	desk := newDesktopApp()

	app := application.New(application.Options{
		Name:        "Tachi",
		Description: "Tachi — AI Agent desktop companion",
		Services: []application.Service{
			application.NewService(&AgentService{desk: desk}),
		},
		Assets: application.AssetOptions{
			Handler: assetHandler(assets),
		},
		Mac: application.MacOptions{
			// Keep the app alive in the menu bar when the window closes.
			ApplicationShouldTerminateAfterLastWindowClosed: false,
		},
	})

	// Appearance: follow the system by default, unless the app has remembered a
	// manual choice from the titlebar switch (desktop_ui.json, mirrored by the
	// frontend) — or a forced value from TACHI_DESKTOP_APPEARANCE (dev aid),
	// which outranks both. Resolving this BEFORE the window exists is what keeps
	// a manual dark theme from flashing a light frame on launch.
	storedTheme := loadUIState().Theme
	forcedTheme := forcedAppearance()
	appearance, dark := resolveTheme(storedTheme, forcedTheme, app.Env.IsDarkMode())
	background := windowBgLight
	if dark {
		background = windowBgDark
	}

	// Main conversational window.
	// Native macOS title bar is hidden but its traffic-light buttons remain
	// (like Zed): MacTitleBarHidden keeps the standard red/yellow/green controls
	// in the top-left while the content fills the window. InvisibleTitleBarHeight
	// gives the top region a drag handle.
	window := app.Window.NewWithOptions(application.WebviewWindowOptions{
		Title:     "Tachi",
		Width:     1200,
		Height:    780,
		MinWidth:  900,
		MinHeight: 600,
		Mac: application.MacWindow{
			InvisibleTitleBarHeight: 44,
			// Opaque window: the UI is a flat, solid design (no vibrancy, no
			// backdrop blur anywhere), so the desktop behind the window must
			// not bleed through.
			Backdrop: application.MacBackdropNormal,
			TitleBar: application.MacTitleBarHidden,
			// The appearance resolved above: the user's remembered choice, the
			// dev override, or DefaultAppearance (= follow the system, which is
			// also what an untouched switch resolves to).
			Appearance: appearance,
		},
		// Matches --bg in base.css for the current theme, so the window never
		// flashes a different shade before the frontend paints. Kept in step by
		// themeController once the frontend is running.
		BackgroundColour: background,
		// Native drag-and-drop of files onto the window. Drops only register
		// on elements marked data-file-drop-target (the composer), and the
		// webview cannot read the paths itself — they arrive in Go via the
		// WindowFilesDropped event below and are forwarded to the frontend.
		EnableFileDrop: true,
		URL:            "/",
	})
	desk.app = app
	desk.window = window

	// Native notifications for the two moments the app waits on the user (a
	// finished turn, a parked AskUserQuestion). They are posted only while the
	// window is unfocused; permission is asked once, in the background, so the
	// prompt is not tied to the first notification. See desktop/notify.go.
	desk.notify = newNotifier(window)
	desk.notify.onNotificationClick()
	go desk.notify.requestAuthorization()

	// Forward native file drops to the frontend, which inserts @-references
	// into the input area. The element id lets the frontend decide where the
	// drop landed (and ignore drops outside the drop targets).
	window.OnWindowEvent(events.Common.WindowFilesDropped, func(e *application.WindowEvent) {
		elementID := ""
		if dt := e.Context().DropTargetDetails(); dt != nil {
			elementID = dt.ElementID
		}
		desk.emitFileDrop(e.Context().DroppedFiles(), elementID)
	})

	// Keep the window background in step with the theme while the app runs:
	// the frontend mirrors every switch over uiThemeEventName (it owns the
	// choice — its inline boot script is what paints the first frame), and the
	// system-appearance listener covers the pre-paint colour and the frame
	// around the webview. Both are no-ops while a manual choice or the dev
	// override owns the theme (see themeController).
	themes := newThemeController(window, storedTheme, forcedTheme)
	app.Event.On(uiThemeEventName, func(e *application.CustomEvent) {
		if theme, ok := e.Data.(string); ok {
			themes.setFromFrontend(theme)
		}
	})
	app.Event.OnApplicationEvent(events.Mac.ApplicationDidChangeTheme, func(*application.ApplicationEvent) {
		themes.onSystemChange(app.Env.IsDarkMode())
	})

	// Menu bar item reflecting the agent state.
	desk.tray = setupTray(desk)

	// Initial state broadcast (drives tray label/icon + frontend status bar).
	desk.setSessionState("", AgentState{Status: StatusIdle, Label: "空闲", Detail: "就绪"})

	// Boot the real tachi agent (falls back to simulated turns on failure).
	if err := desk.initAgent(context.Background()); err != nil {
		log.Printf("agent unavailable, falling back to simulated turns: %v", err)
		desk.setSessionState("", AgentState{Status: StatusIdle, Label: "空闲", Detail: "未配置 agent（模拟模式）"})
	}

	// Optional self-test driver (TACHI_DEMO): inject JS to type & send from
	// within the webview, so we can exercise input + state transitions without
	// relying on system-level mouse/keyboard coordinates.
	if demoEnabled() {
		go runJsDemo(window)
	}

	// Run the application.
	if err := app.Run(); err != nil {
		log.Fatal(err)
	}
	desk.teardownAgent()
}
