package main

// Bash 权限确认：策略 `ask` 在 desktop 上落到一张原生确认卡。
//
// 背景：desktop 原来用 agent.PermissionModeSkip，那个模式的 `ask` 分支是按「无人值守」设计的
// （channel / subagent / `tachi -p`——没有人在终端前），所以命中 ask 规则时直接拒绝，并回一句
// 「请让用户加 allow 规则」。可是 desktop 的用户就在窗口前面，GUI 也已经会渲染提问表单，于是
// 用户自己写进 config.yaml 的 ask 规则在唯一一个「看得见人」的前端上反而成了硬拒绝。
//
// 修法不是给 agent 层加第四个 PermissionMode：`PermissionModeExternal` 的语义本来就是「交给外部
// 主体决定」，ACP 就是这么接的（agent/acp/permission.go）。desktop 与它同构——一个带着真人的
// 外部主体——所以这里只实现一个 PermissionHandler，把决策通过事件送进窗口，等前端回填。
//
// 与 AskUserQuestion 是同一套「挂起—回答」范式（见 askuser.go）：handler 阻塞在 channel 上，
// binding 负责叫醒它。区别只有一个：AskUser 的答案走 agent 自己的 channel（RespondToAskUser），
// 而权限的决策完全属于前端，所以待确认表由 desktop 自己持有。

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/monsterxx03/tachi/agent"
)

// PermissionEvent is emitted to the frontend when a bash command matched an
// `ask` rule and the turn is parked on the user's decision. The answer goes back
// through AgentService.AnswerPermission.
//
// Preview is the agent's own rendering of what is being asked ($ command + the
// matched rule, see bashAskPreview on the agent side) and is shown verbatim: a
// second parser of that format here would be free to drift from the one that
// writes it.
type PermissionEvent struct {
	SessionID string `json:"sessionId"`
	ToolID    string `json:"toolId"`
	ToolName  string `json:"toolName"`
	Preview   string `json:"preview"`
}

// The decisions the confirm card can send. `allow_always` mirrors the TUI's `a`
// (approve this call and remember the exact command for the rest of the
// session) rather than ACP's allow-all — switching the whole session to Skip
// would also switch off the deny rules the user wrote.
const (
	permAllowOnce   = "allow_once"
	permAllowAlways = "allow_always"
	permDeny        = "deny"
)

// pendingPermission is one parked ask: the channel its answer arrives on. The session
// and tool call it belongs to are in its key (permKey) — the row exists for the wait,
// nothing else needs to be read back out of it.
type pendingPermission struct {
	answer chan string
}

// noAskKey marks a run whose conversation has no turn on screen.
//
// A side-channel run (/review, /commit) reports into the panel's lane, not into the
// transcript, so there is nowhere to render a confirm card — parking it on a user
// decision would hang a run nobody can answer. The desktop marks its own one-off ctx
// (commands.go) instead of asking the agent layer to tell us: the lane is a desktop
// concept, and the marker must not leak into the other frontends' behaviour.
type noAskKey struct{}

func withoutAsk(ctx context.Context) context.Context { return context.WithValue(ctx, noAskKey{}, true) }

// askable reports whether this run has somewhere to ask the user.
func askable(ctx context.Context) bool {
	v, _ := ctx.Value(noAskKey{}).(bool)
	return !v
}

// permKey keyes a pending ask by session AND tool call. The tool call id alone is
// generated by the model, so two sessions can produce the same one; keying by the
// pair is what keeps an answer from reaching another conversation's ask.
func permKey(sessionID, toolID string) string { return sessionID + "\x00" + toolID }

// permissionHandler builds the PermissionHandler installed on one session's agent.
// `a` is captured for AllowExactSession (the "本会话始终允许" decision records the
// command on that session's own policy — the policy is built per agent, see
// agent_configure.go).
func (d *desktopApp) permissionHandler(sessionID string, a *agent.AIAgent) agent.PermissionHandler {
	return func(ctx context.Context, toolName, toolID, preview, args string) (bool, error) {
		return d.askPermission(ctx, sessionID, a, toolName, toolID, preview, args)
	}
}

// askPermission parks the agent goroutine until the user answers, then reports
// the decision as (approved, error).
//
// A cancelled context (Stop, or the app going away) releases the wait: the tool
// result then carries the cancellation, which is the same shape the TUI and ACP
// paths produce.
func (d *desktopApp) askPermission(ctx context.Context, sessionID string, a *agent.AIAgent, toolName, toolID, preview, args string) (bool, error) {
	// No turn on screen (a side-channel run): refuse with the explanation the agent's own
	// unattended branch gives, rather than parking a run that has no card to answer in.
	if !askable(ctx) {
		return false, fmt.Errorf("command requires interactive approval (matched an ask rule), "+
			"but a side-channel run has no conversation turn to confirm it in — the command was NOT "+
			"executed. Add an allow rule to permissions.bash to run it here (preview: %s)", preview)
	}
	key := permKey(sessionID, toolID)
	answer := make(chan string, 1)

	d.mu.Lock()
	if d.perms == nil {
		d.perms = make(map[string]*pendingPermission)
	}
	d.perms[key] = &pendingPermission{answer: answer}
	d.mu.Unlock()
	// Always drop the entry, whichever way the wait ends: a stale pending ask
	// would let a late click approve a command that is no longer running.
	defer func() {
		d.mu.Lock()
		delete(d.perms, key)
		d.mu.Unlock()
	}()

	// The turn is parked on the user, so say so — the same status the parked
	// AskUserQuestion uses (setSessionState only reaches the UI when this IS the
	// displayed session, so a background ask cannot hijack the foreground).
	d.setSessionState(sessionID, AgentState{Status: StatusBusy, Label: "授权", Detail: "等待确认"})
	if d.app != nil {
		d.app.Event.Emit("agent:permission", PermissionEvent{
			SessionID: sessionID,
			ToolID:    toolID,
			ToolName:  toolName,
			Preview:   preview,
		})
	}
	d.notify.notifyPermission(d.sessionTitle(sessionID), bashCommandOf(args))

	select {
	case decision := <-answer:
		if decision == permAllowAlways {
			// Only a real command is remembered: an unparsable call cannot be the
			// exact command the user chose, and recording "" would put a junk key
			// in the session's approval set.
			if cmd := bashCommandOf(args); cmd != "" {
				if p := a.PermissionPolicy(); p != nil {
					p.AllowExactSession(cmd)
				}
			}
		}
		return decision != permDeny, nil
	case <-ctx.Done():
		return false, ctx.Err()
	}
}

// AnswerPermission delivers the user's decision for a parked ask, unblocking the
// agent loop. sessionID + toolID must name the ask that is actually waiting: the
// frontend answers with the id it was given, so a card left over from an earlier
// call (or another conversation) is refused instead of approving something else.
func (s *AgentService) AnswerPermission(sessionID, toolID, decision string) string {
	d := s.desk
	if decision != permAllowOnce && decision != permAllowAlways && decision != permDeny {
		return "unknown decision"
	}

	d.mu.Lock()
	perm := d.perms[permKey(sessionID, toolID)]
	d.mu.Unlock()
	if perm == nil {
		return "no such pending request"
	}

	select {
	case perm.answer <- decision:
		return "ok"
	default:
		// Buffered with capacity 1 and deleted by the waiting goroutine, so this
		// is unreachable unless the same ask is answered twice in the same
		// instant — refused rather than blocking the frontend's call.
		return "already answered"
	}
}

// bashCommandOf extracts the "command" field of a Bash tool call's arguments. It
// parses the TOOL's own arguments (the same JSON the tool and the agent's own
// policy check read), not any rendering of them, and a parse failure is simply
// "no command" — an unparsable call cannot be the exact command the user chose to
// remember, so AllowExactSession is skipped rather than remembered wrong.
func bashCommandOf(args string) string {
	var a struct {
		Command string `json:"command"`
	}
	if err := json.Unmarshal([]byte(args), &a); err != nil {
		return ""
	}
	return a.Command
}
